/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Lenovo
 */

import admin.AdminForm;
import karyawan.form_gaji;
import login.frlogin;
import static main.frmain.mlogin;
import static main.frmain.mlogout;

public final class frmain extends javax.swing.JFrame {

    /**
     * Creates new form frmain
     */
    public frmain() {
        initComponents();
        aksesLogout();
    }
    
    public void aksesLogout() {
        mlogout.setEnabled(false);
        mlogin.setEnabled(true);
        Bgaji.setEnabled(false);
        dtAdmin.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        akses = new javax.swing.JMenu();
        mlogin = new javax.swing.JMenuItem();
        mlogout = new javax.swing.JMenuItem();
        data = new javax.swing.JMenu();
        dtAdmin = new javax.swing.JMenuItem();
        bayarGaji = new javax.swing.JMenu();
        Bgaji = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        akses.setText("Akses");

        mlogin.setText("login");
        mlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mloginActionPerformed(evt);
            }
        });
        akses.add(mlogin);

        mlogout.setText("logout");
        mlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlogoutActionPerformed(evt);
            }
        });
        akses.add(mlogout);

        jMenuBar1.add(akses);

        data.setText("Data");

        dtAdmin.setText("Karyawan");
        dtAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtAdminActionPerformed(evt);
            }
        });
        data.add(dtAdmin);

        jMenuBar1.add(data);

        bayarGaji.setText("Bayar Gaji");

        Bgaji.setText("Karyawan");
        Bgaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BgajiActionPerformed(evt);
            }
        });
        bayarGaji.add(Bgaji);

        jMenuBar1.add(bayarGaji);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1051, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mloginActionPerformed
        // TODO add your handling code here:
        new frlogin().setVisible(true);
    }//GEN-LAST:event_mloginActionPerformed

    private void mlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlogoutActionPerformed
        // TODO add your handling code here:
        aksesLogout();
    }//GEN-LAST:event_mlogoutActionPerformed

    private void BgajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BgajiActionPerformed
        // TODO add your handling code here:
        new form_gaji().setVisible(true);
    }//GEN-LAST:event_BgajiActionPerformed

    private void dtAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtAdminActionPerformed
        // TODO add your handling code here:
        new AdminForm().setVisible(true);
    }//GEN-LAST:event_dtAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuItem Bgaji;
    private javax.swing.JMenu akses;
    private javax.swing.JMenu bayarGaji;
    private javax.swing.JMenu data;
    public static javax.swing.JMenuItem dtAdmin;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem mlogin;
    public static javax.swing.JMenuItem mlogout;
    // End of variables declaration//GEN-END:variables
}
